[phases.setup]
nixPkgs = ["python39", "chromium", "chromedriver"]

[phases.install]
cmds = [
  "cd backend && python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && . venv/bin/activate && python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"

